name: env
description: Build the environment file

inputs:
  next_public_api_key:
    description: service account key
    required: true
  next_public_app_url:
    description: app url
    required: true
  next_public_api_host:
    description: project id
    required: true
  next_public_google_map_api_key:
    description: google map key
    required: true
  next_public_auth0_domain:
    description: auth0 domain
    required: true
  next_public_auth0_client_id:
    description: auth0 client id
    required: true
  next_public_auth0_audience:
    description: auth0 audience
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Create the configuration folder'
      shell: bash
      run: |
        mkdir ./configuration
      working-directory: .

    - name: 'Create the .env file'
      shell: bash
      run: |
        echo "
        NEXT_PUBLIC_API_KEY=${{ inputs.next_public_api_key }}
        NEXT_PUBLIC_APP_URL=${{ inputs.next_public_app_url }}
        NEXT_PUBLIC_API_HOST=${{ inputs.next_public_api_host }}
        NEXT_PUBLIC_GOOGLE_MAP_API_KEY=${{ inputs.next_public_google_map_api_key }}
        NEXT_PUBLIC_AUTH0_DOMAIN=${{ inputs.next_public_auth0_domain }}
        NEXT_PUBLIC_AUTH0_CLIENT_ID=${{ inputs.next_public_auth0_client_id }}
        NEXT_PUBLIC_AUTH0_AUDIENCE=${{ inputs.next_public_auth0_audience }}" > .env.production
      working-directory: ./configuration

    - name: 'cat the .env file'
      shell: bash
      run: |
        cat .env.production
      working-directory: ./configuration

    - name: 'Zip the configuration folder'
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r configuration.zip ./configuration

    - name: 'Upload configuration artifact'
      uses: actions/upload-artifact@v3
      with:
        name: configuration
        path: ./configuration.zip
