name: Checks
description: Build and deploy the app to the specified environment

runs:
  using: 'composite'
  steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: 'list files'
      shell: bash
      run: |
        ls -larth

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Setup pnpm environment
      uses: pnpm/action-setup@v2
      with:
        version: 8.6.5

    - name: Build and test
      shell: bash
      run: |
        pnpm i
        pnpm build
        pnpm test:once
      working-directory: .
