import { ProjectDetails } from '@/@types/ProjectDetails'

export const projectDetail: ProjectDetails = {
  warehouseProjectId: `01d919c9-dc5a-489e-9826-c08b6850bbcb`,
  id: `79`,
  name: `Carbono Verde`,
  description: `Develop and register a project for the removal of GHG emissions from forest plantations with Teak, Gmelina and Eucalyptus established in the Municipalities of Puerto Libertador (Córdoba) and Tolú (Sucre).`,
  standard: `EcoRegistry`,
  methodology: `AR-ACM0003: Afforestation and reforestation of lands except wetlands`,
  developer: `Forestry Consulting Group S.A.S.`,
  sector: `Agriculture; forestry and fishing`,
  type: `Reforestation and Revegetation`,
  location: {
    country: `Colombia`,
    region: `Puerto Libertador`,
    geoCoordinates: `{"latitude": 7.890035309322826, "longitude": -75.67111616574155}`,
  },
  link: `https://www.ecoregistry.io/projects/79`,
  tags: `More information in the project link. || Cercarbono Standard. || Sectors of project: Agriculture; forestry and fishing . || Methodologies of project: AR-ACM0003: Afforestation and reforestation of lands except wetlands . || Latest or current Validation Number: 1 . || Latest or current Verification Number: 1`,
  coveredByNdc: `Unknown`,
  status: `Registered`,
  statusDate: `2021-04-15T00:52:54.825Z`,
  coBenefits: [
    `SDG 8 - Decent work and economic growth`,
    `SDG 15 - Life on land`,
    `SDG 13 - Climate action`,
    `SDG 9 - Industry, innovation, and infrastructure`,
    `SDG 7 - Affordable and clean energy`,
    `SDG 4 - Quality education`,
  ],
  creditingPeriodStart: `2011-05-23T00:00:00.000Z`,
  creditingPeriodEnd: `2030-05-22T00:00:00.000Z`,
  validation: {
    body: `Colombian Institute for Technical Standards and Certification (ICONTEC)`,
    date: `2023-04-15T00:52:54.825Z`,
    verifications: [],
  },
  units: {
    estimated: 127855,
    issued: 0,
    retired: 0,
    available: 0,
    creditingPeriodStart: `2011-05-23T00:00:00.000Z`,
    creditingPeriodEnd: `2030-05-22T00:00:00.000Z`,
    unitMetric: `tCO2e`,
  },
  issuances: [],
  documents: [],
}
