export const MockRegionsData = [
  { value: `africa`, label: `regions.africa`, isHeader: true },
  { value: `northern-africa`, label: `regions.northern-africa` },
  { value: `sub-saharan-africa`, label: `regions.sub-saharan-africa` },
  { value: `americas`, label: `regions.americas`, isHeader: true },
  { value: `latin-america-and-the-caribbean`, label: `regions.latin-america-and-the-caribbean` },
  { value: `northern-america`, label: `regions.northern-america` },
  { value: `asia`, label: `regions.asia`, isHeader: true },
  { value: `central-asia`, label: `regions.central-asia` },
  { value: `eastern-asia`, label: `regions.eastern-asia` },
  { value: `southern-asia`, label: `regions.southern-asia` },
  { value: `south-eastern-asia`, label: `regions.south-eastern-asia` },
  { value: `western-asia`, label: `regions.western-asia` },
  { value: `europe`, label: `regions.europe`, isHeader: true },
  { value: `eastern-europe`, label: `regions.eastern-europe` },
  { value: `northern-europe`, label: `regions.northern-europe` },
  { value: `southern-europe`, label: `regions.southern-europe` },
  { value: `western-europe`, label: `regions.western-europe` },
  { value: `oceania`, label: `regions.oceania`, isHeader: true },
  { value: `australia-and-new-zealand`, label: `regions.australia-and-new-zealand` },
  { value: `melanesia`, label: `regions.melanesia` },
  { value: `micronesia`, label: `regions.micronesia` },
  { value: `polynesia`, label: `regions.polynesia` },
]
