name: Deploy build content to bucket
description: Deploy Content into bucket

inputs:
  service_account_key:
    description: Service account key
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Setup pnpm environment
      uses: pnpm/action-setup@v2
      with:
        version: 6.0.2

    - name: Build and test
      shell: bash
      run: |
        pnpm i
        pnpm build
      working-directory: .

    - name: 'Google auth'
      id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ inputs.service_account_key }}'

    - name: Upload static content to bucket
      uses: google-github-actions/upload-cloud-storage@v1
      with:
        path: 'out'
        destination: 'cad-trust-dev-static-bucket'
        parent: false


